name: Build APK Manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (Bypass Signing)
        run: |
          keytool -genkey -v -keystore android/dummy.keystore -alias dummykey -keyalg RSA -keysize 2048 -validity 10000 -storepass dummy123 -keypass dummy123 -dname "CN=Dummy,O=Dummy,C=US"
          echo "keyAlias=dummykey" > android/key.properties
          echo "keyPassword=dummy123" >> android/key.properties
          echo "storePassword=dummy123" >> android/key.properties
          echo "storeFile=dummy.keystore" >> android/key.properties
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anx-reader-release
          path: build/app/outputs/flutter-apk/app-release.apk
